### ISSUE TITLE
More clear example

### ISSUE THREAD

**Issue by iamolegga** [matpaul/react-with#1]
Hi, @matpaul ✋ i'm just wondering about your example

```jsx
import React from 'react';
import With from 'react-with';

const onToggle = ({ state, setState }, event) =>
  setState(state => ({ on: !state.on }));

const Toggle = ({ children, initial }) => (
  <With state={{ on: initial }} toggle={onToggle}>
  {({ on, toggle }) => (
    <button onClick={toggle}>Button: {on ? 'on' : 'off'}</button>
  )}
  </With>
);
```

Here I have some misunderstanding with `onToggle` because of variable shadowing, i mean `state`, here it comes from `onToggle` first argument destructuring and next the same name is also uses for `setState` first argument

**Comment by matpaul** [comment]
Hi @iamolegga, yep it's just show what params in first argument, 
you can submit pr with fix example)

**Comment by matpaul** [comment]
@iamolegga also I think this types of libs not need because react hooks is landing ))
